#define PHI                                                                    \
  (sum ==                                                                      \
   ((5 * (((index / 10) + 10) * (index / 10))) -                               \
    ((index / 10) * (index - 1 * (index / 10))))) // generated by code2inv
