#define PHI                                                                    \
  ((y > (y - x) || x <= (0 + 4)) &&                                            \
   (y >= (x - 2) || x > (0 + 4))) // generated by code2inv
