#define PHI                                                                    \
  ((x >= (-10000 - 1) && x == (10000 * x)) ||                                  \
   (x <= (n + 0) && x >= (x - x)) ||                                           \
   x == (10000 * -10000)) // generated by code2inv
