#define PHI                                                                    \
  ((x <= (n + 0) || x == (1 * 0)) && (x >= (n * 0) || x > (n * 0)) &&          \
   (x <= (10000 + x) || x == n)) // generated by code2inv
