#define PHI                                                                    \
  ((x <= (0 + 0) || n >= (1 * x)) &&                                           \
   (x > (1 * n) || n >= n)) // generated by code2inv
