#define PHI                                                                    \
  ((m >= (0 + 1) || m > (j * a)) && m < (1 - m) &&                             \
   (a < -10000 || m < (j * 0))) // generated by code2inv
