#define PHI                                                                    \
  ((i >= (sn * i) || i >= (i - 1)) && (i < (0 - n) || n > (i * 1)) &&          \
   i >= (sn * sn)) // generated by code2inv
