#define PHI                                                                    \
  ((y <= (i + x) || j > (x - x)) && y >= (x - y) &&                            \
   (y < 10000 || y < (y * 1))) // generated by code2inv
