#define PHI                                                                    \
  ((x >= 1 && y == (1 * y)) ||                                                 \
   (x > (1 - x) && x < (y - 1))) // generated by code2inv
