#define PHI                                                                    \
  (d2 <= 10000 || d1 <= (10000 - x2) ||                                        \
   (x2 > (d2 - 10000) && d1 < d3)) // generated by code2inv
