#define PHI                                                                    \
  ((n > 2) && (n <= n) &&                                                      \
   (isprime(n) && (n == 1 * n) ||                                              \
    !isprime(n) && (n == 2 * n))) // generated by code2inv
