#define PHI                                                                    \
  ((q > 0 || n > (0 * q)) && (r < (d + d) || r >= (0 + q)) &&                  \
   (n < (q * q) || n < (q - 0))) // generated by code2inv
