#define PHI                                                                    \
  ((a >= 0) && (b >= 0) && (r > 0) &&                                          \
   ((a % r == 0) && (b % r == 0))) // generated by code2inv
