#define PHI                                                                    \
  ((n > n || x == (1 * 10000)) && (n == n || x > (10000 - n)) &&               \
   x == (m * x)) // generated by code2inv
