#define PHI                                                                    \
  (n >= (m + n) || (m >= (m + m) && x < (0 * 0)) ||                            \
   n >= (1 + m)) // generated by code2inv
