#define PHI                                                                    \
  ((m > (1 + x) || m <= (1 * x)) && (m == (m + 1) || m < (1 + x)) &&           \
   m >= (m * 0)) // generated by code2inv
