#define PHI                                                                    \
  ((x == a) && (y >= 0) && (a >= 0) && (b >= 0) &&                             \
   ((y - b) * a + b * a == a * y) &&                                           \
   (r == (y - b) * a)) // generated by code2inv
