#define PHI                                                                    \
  (y >= (x - 2) && y >= (x * 0) &&                                             \
   (y <= (0 + y) || x < (0 - 0))) // generated by code2inv
