#define PHI                                                                    \
  ((x > (1 * 0) || j > (x - 1)) && (x < (j - 0) || y <= (1 + 0)) &&            \
   (i <= (y + 1) || y < (x * 1))) // generated by code2inv
