#define PHI                                                                    \
  (i == (y + i) && (y > i || x < i) &&                                         \
   (i == (x + 0) || j > (1 - i))) // generated by code2inv
